/** Green Ledger's own words. An org overrides any of these; none of it affects a calculation. */
import type { LabelEntityKind, SystemDefault } from './index';

export const SYSTEM_DEFAULTS: Record<LabelEntityKind, Record<string, SystemDefault>> = {
  SCOPE: {
    SCOPE_1: { label: 'Scope 1', description: 'Fuel you burn yourself, and gases that leak from your equipment.' },
    SCOPE_2: { label: 'Scope 2', description: 'Energy you buy — electricity, steam, heating, cooling.' },
    SCOPE_3: { label: 'Scope 3', description: 'Everything else in your value chain.' },
  },
  SCOPE3_CATEGORY: {
    scope3_cat_1:  { label: 'Purchased goods and services', shortLabel: '3.1 Purchased goods' },
    scope3_cat_2:  { label: 'Capital goods', shortLabel: '3.2 Capital goods' },
    scope3_cat_3:  { label: 'Fuel- and energy-related activities', shortLabel: '3.3 Fuel & energy' },
    scope3_cat_4:  { label: 'Upstream transportation and distribution', shortLabel: '3.4 Upstream freight' },
    scope3_cat_5:  { label: 'Waste generated in operations', shortLabel: '3.5 Waste' },
    scope3_cat_6:  { label: 'Business travel', shortLabel: '3.6 Business travel' },
    scope3_cat_7:  { label: 'Employee commuting', shortLabel: '3.7 Commuting' },
    scope3_cat_8:  { label: 'Upstream leased assets', shortLabel: '3.8 Upstream leased' },
    scope3_cat_9:  { label: 'Downstream transportation and distribution', shortLabel: '3.9 Downstream freight' },
    scope3_cat_10: { label: 'Processing of sold products', shortLabel: '3.10 Processing' },
    scope3_cat_11: { label: 'Use of sold products', shortLabel: '3.11 Product use' },
    scope3_cat_12: { label: 'End-of-life of sold products', shortLabel: '3.12 End of life' },
    scope3_cat_13: { label: 'Downstream leased assets', shortLabel: '3.13 Downstream leased' },
    scope3_cat_14: { label: 'Franchises', shortLabel: '3.14 Franchises' },
    scope3_cat_15: { label: 'Investments', shortLabel: '3.15 Investments' },
  },
  ACTIVITY_TYPE: {
    STATIONARY_COMBUSTION: { label: 'Stationary combustion', description: 'Fuel burned in fixed equipment — boilers, generators, furnaces.' },
    MOBILE_COMBUSTION:     { label: 'Mobile combustion', description: 'Fuel burned in vehicles and mobile plant you control.' },
    FUGITIVE:              { label: 'Fugitive emissions', description: 'Gases that escape — refrigerants, SF6.' },
    PROCESS:               { label: 'Process emissions' },
    PURCHASED_ELECTRICITY: { label: 'Purchased electricity' },
    PURCHASED_HEAT:        { label: 'Purchased heat' },
    PURCHASED_STEAM:       { label: 'Purchased steam' },
    PURCHASED_COOLING:     { label: 'Purchased cooling' },
    SPEND:                 { label: 'Spend' },
    DISTANCE:              { label: 'Distance travelled' },
    MASS:                  { label: 'Mass' },
    WASTE:                 { label: 'Waste' },
    OTHER:                 { label: 'Other' },
  },
  METHOD: {
    FUEL_BASED:          { label: 'Fuel-based' },
    DISTANCE_BASED:      { label: 'Distance-based' },
    SPEND_BASED:         { label: 'Spend-based' },
    AVERAGE_DATA:        { label: 'Average data' },
    SUPPLIER_SPECIFIC:   { label: 'Supplier-specific' },
    WASTE_TYPE_SPECIFIC: { label: 'Waste-type-specific' },
    MATERIAL_BASED:      { label: 'Material-based' },
    HYBRID:              { label: 'Hybrid' },
  },
  DATA_QUALITY: {
    MEASURED:   { label: 'Measured', description: 'From a meter or an invoice.' },
    CALCULATED: { label: 'Calculated', description: 'Derived from other measured data.' },
    ESTIMATED:  { label: 'Estimated', description: 'A reasoned estimate.' },
    PROXY:      { label: 'Proxy', description: 'Stood in from a similar site or an industry average.' },
  },
  ASSET_CATEGORY: {
    STATIONARY_COMBUSTION: { label: 'Stationary combustion' },
    MOBILE_COMBUSTION:     { label: 'Mobile combustion' },
    REFRIGERATION:         { label: 'Refrigeration' },
    PROCESS:               { label: 'Process' },
    ON_SITE_GENERATION:    { label: 'On-site generation' },
    ELECTRICAL:            { label: 'Electrical' },
    WASTE_HANDLING:        { label: 'Waste handling' },
    IT_EQUIPMENT:          { label: 'IT equipment' },
    OTHER:                 { label: 'Other' },
  },
  ASSET_TYPE: {},
  SITE_TYPE: {},
  FUEL_OR_MATERIAL: {},
  DENOMINATOR: {
    floor_area_m2: { label: 'Floor area', shortLabel: 'm²' },
    headcount_fte: { label: 'FTE headcount', shortLabel: 'FTE' },
    revenue:       { label: 'Revenue' },
  },
  UNIT: {
    L: { label: 'Litres' }, M3: { label: 'Cubic metres', shortLabel: 'm³' },
    GAL_US: { label: 'US gallons' }, GAL_UK: { label: 'UK gallons' },
    G: { label: 'Grams' }, KG: { label: 'Kilograms', shortLabel: 'kg' },
    TONNE: { label: 'Tonnes', shortLabel: 't' }, LB: { label: 'Pounds' },
    KWH: { label: 'Kilowatt-hours', shortLabel: 'kWh' }, MWH: { label: 'Megawatt-hours', shortLabel: 'MWh' },
    GJ: { label: 'Gigajoules' }, MJ: { label: 'Megajoules' },
    THERM: { label: 'Therms' }, MMBTU: { label: 'MMBtu' },
    KM: { label: 'Kilometres', shortLabel: 'km' }, MI: { label: 'Miles' }, NM: { label: 'Nautical miles' },
    TONNE_KM: { label: 'Tonne-kilometres' }, KG_KM: { label: 'Kilogram-kilometres' },
    PASSENGER_KM: { label: 'Passenger-kilometres' },
    GBP: { label: 'Pounds sterling' }, EUR: { label: 'Euros' }, USD: { label: 'US dollars' },
    INR: { label: 'Indian rupees' }, CAD: { label: 'Canadian dollars' },
    KG_CO2E: { label: 'kg CO₂e' }, T_CO2E: { label: 'tonnes CO₂e' },
    KG_CO2: { label: 'kg CO₂' }, KG_CH4: { label: 'kg CH₄' }, KG_N2O: { label: 'kg N₂O' },
    UNIT: { label: 'Units' },
  },
  STATUS: {
    NOT_STARTED: { label: 'Not started' }, IN_PROGRESS: { label: 'In progress' },
    IN_REVIEW: { label: 'In review' }, APPROVED: { label: 'Approved' }, LOCKED: { label: 'Locked' },
    DRAFT: { label: 'Draft' }, SUBMITTED: { label: 'Submitted' }, REJECTED: { label: 'Rejected' },
    UNANSWERED: { label: 'Unanswered' }, ANSWERED: { label: 'Answered' }, FLAGGED: { label: 'Flagged' },
  },
  SECTION: {},
  QUESTION: {},
  ROLE: {
    OWNER: { label: 'Owner' }, ADMIN: { label: 'Admin' }, CONTRIBUTOR: { label: 'Contributor' },
    APPROVER: { label: 'Approver' }, AUDITOR: { label: 'Auditor' },
  },
  DOCUMENT_TYPE: {
    INVOICE: { label: 'Invoice' }, METER_READ: { label: 'Meter read' }, CONTRACT: { label: 'Contract' },
    EAC_CERTIFICATE: { label: 'Energy attribute certificate' }, METHODOLOGY: { label: 'Methodology note' },
    ASSURANCE: { label: 'Assurance evidence' }, OTHER: { label: 'Other' },
  },
};
